### PR TITLE
HSDO-527: Change the search and replace to file styles only

### PR DESCRIPTION
**Pull request by sherakama**
Adding /styles/ to the search and replace token in order to avoid re-writing paths to the image source or non-image files.

### CODE REVIEW

**Comment by jbickar** [comment]
Can't do that, Batman. Look at the commit history.

**Comment by jbickar** [comment]
Oh wait, that might work. That'll teach me to comment on my phone.

**Comment by sherakama** [comment]
wait, I must have updated from an older version. My only change is adding a forward slash. This PR might not be needed.

**Comment by sherakama** [comment]
Fix was already in play. Just needed to update to latest.

**Comment by jbickar** [comment]
Thanks, Past John.

**Pull request closed without merging**
