### PR TITLE
Enable caching and disable logging

### PR DESCRIPTION
**Pull request by jbickar**
**READY**

### CODE REVIEW

**Comment by jbickar** [comment]
:+1:

**Comment by jbickar** [comment]
I un-deleted the branch, just in case we want to re-visit ANCH-68 ever again.

**Comment by sherakama** [comment]
I'd rather have the branch go away. There is no code in it that isn't in the 7.x-1.x branch and we have the history on the ticket. 

also, we should be putting the ticket number before our commit messages. We have gotten slack with that convention.

**Comment by jbickar** [comment]
OK, you convinced me. Added a note to the ticket pointing to the specific commit.

**Pull request merged**
